### ISSUE TITLE
Health check fails when deployed via action-deploy, but works when deploying locally.

### ISSUE THREAD

**Issue by Cameron-C-Chapman** [convox/action-deploy#2]
I'm trying to deploy an app via convox on a merge to master using Github Actions, and cannot figure out why my health check is failing when deployed from the Github Action vm, but not when I deploy locally.

It's a really straightforward checkout -> deploy workflow, and the exact same workflow works from my local command line with the same branch/source. The task just won't report back a successful health check, and won't cutover to the new instance that was deployed.

This is app is deployed to AWS and I've looked at the container definitions and everything looks identical.

Here's my deploy.yml file:
```
name: deploy

on:
  push:
    branches:    
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: convox/action-deploy@v1
      with:
        host: console.convox.com
        rack: ${{ secrets.CONVOX_RACK }}
        app: orchestrator
        password: ${{ secrets.CONVOX_CLI_KEY }}
```

and here's what happens in the Github Action vm, but not locally:

![image](https://user-images.githubusercontent.com/1323581/89451115-50571b80-d721-11ea-80fc-f7c9c2ceb4e9.png)

Is there something simple I'm missing here or any suggestions on what might be the issue?
